### ISSUE TITLE
Missing libout123 dependency

### ISSUE THREAD

**Issue by majcherek2048** [NolanNicholson/Looper#2]
libout123 is a dependency too.

```
Playing with loop from 02:47.523 back to 01:23.122 (78% match)
(press Ctrl+C to exit)
Traceback (most recent call last):
  File "loop.py", line 174, in <module>
    loop_track(sys.argv[1])
  File "loop.py", line 165, in loop_track
    track.play_looping(start_offset, best_offset)
  File "loop.py", line 140, in play_looping
    out = Out123()
  File "/usr/local/lib/python3.5/dist-packages/mpg123.py", line 274, in __init__
    self._lib = self.init_library(library_path)
  File "/usr/local/lib/python3.5/dist-packages/mpg123.py", line 263, in init_library
    raise self.LibInitializationException('libout123 not found')
mpg123.LibInitializationException: libout123 not found
```

**Comment by majcherek2048** [comment]
Just realized that it actually said so on the front-page, by listing mpg123 as an external requirement
