### ISSUE TITLE
mpg123.LibInitializationException: libout123 not found

### ISSUE THREAD

**Issue by pulketo** [NolanNicholson/Looper#5]
I installed with:
pip3 install -r requirements.txt
python3 ~/gits/Looper/loop.py Arriba\ Arriba\ \(Extended\ Mix\)-5ySKv0hUrIE.mp3

and i'm getting this error:
Loading Arriba Arriba (Extended Mix)-5ySKv0hUrIE.mp3...
Playing with loop from 03:08.088 back to 01:39.480 (61% match)
(press Ctrl+C to exit)
Traceback (most recent call last):
  File "/home/pkssd/gits/Looper/loop.py", line 174, in <module>
    loop_track(sys.argv[1])
  File "/home/pkssd/gits/Looper/loop.py", line 165, in loop_track
    track.play_looping(start_offset, best_offset)
  File "/home/pkssd/gits/Looper/loop.py", line 140, in play_looping
    out = Out123()
  File "/home/pkssd/.local/lib/python3.5/site-packages/mpg123.py", line 274, in __init__
    self._lib = self.init_library(library_path)
  File "/home/pkssd/.local/lib/python3.5/site-packages/mpg123.py", line 263, in init_library
    raise self.LibInitializationException('libout123 not found')
**mpg123.LibInitializationException: libout123 not found**

**Comment by nvictor** [comment]
mac users: if you have homebrew do `brew install mpg123` and it will install the libraries you need.

@NolanNicholson i came here from the article and this is a real gem 👍
