### ISSUE TITLE
mpg123

### ISSUE THREAD

**Issue by Kirbeast** [NolanNicholson/Looper#8]
I don't think I installed mpg123 correctly, I can't find anything on how to install it. When I run the python3 loop.py track.mp3 command with an mp3 I get this error.
``Traceback (most recent call last):
  File "loop.py", line 174, in <module>
    loop_track(sys.argv[1])
  File "loop.py", line 157, in loop_track
    track = MusicFile(filename)
  File "loop.py", line 11, in __init__
    mp3 = Mpg123(filename)
  File "C:\Users\kirbe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\mpg123.py", line 110, in __init__
    self._lib = self.init_library(library_path)
  File "C:\Users\kirbe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\mpg123.py", line 101, in init_library
    lib = ctypes.CDLL(library_path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found``
I don't know wtf I did wrong, I don't know how to get your program working. I can't find any good info on mpg123. I just dragged the executables from this [](https://www.mpg123.de/download/win64/1.25.13/)
into the folder with your program in it, then ran the program.
I'm on a Win 10 64bit operating system.

**Comment by JGiubardo** [comment]
I'm not sure what the best way to install it on Windows is, but what I did was grab the libmpg123-0.dll from inside the zip that you can get from https://www.mpg123.de/download/win64/1.25.13/

Then I put that dll inside of C:/Windows
